language: php

php:
  - 7.2
  - 7.3

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer update --no-interaction --prefer-dist --no-progress
  - cd $TRAVIS_BUILD_DIR

script:
  - composer check-all
